version: "3.9"
services:
  myapp:
    image: ghcr.io/diaaqassem/todo-list-nodejs:latest
    ports:
      - "3000:4000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
